///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CDevGlobal_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CDevGlobal_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f6720719-64a7-45e7-b71a-f1aaf4b79e06")]
    public partial class CDevGlobal_DemoRepository : RepoGenBaseFolder
    {
        static CDevGlobal_DemoRepository instance = new CDevGlobal_DemoRepository();
        CDevGlobal_DemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the CDevGlobal_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("f6720719-64a7-45e7-b71a-f1aaf4b79e06")]
        public static CDevGlobal_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CDevGlobal_DemoRepository() 
            : base("CDevGlobal_DemoRepository", "/", null, 0, false, "f6720719-64a7-45e7-b71a-f1aaf4b79e06", ".\\RepositoryImages\\CDevGlobal_DemoRepositoryf6720719.rximgres")
        {
            _applicationundertest = new CDevGlobal_DemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f6720719-64a7-45e7-b71a-f1aaf4b79e06")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b2ab276e-809d-4d9a-9332-135f838ab46e")]
        public virtual CDevGlobal_DemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CDevGlobal_DemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b2ab276e-809d-4d9a-9332-135f838ab46e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "b2ab276e-809d-4d9a-9332-135f838ab46e", "")
            {
                _fnameInfo = new RepoItemInfo(this, "Fname", ".//input[#'FirstName']", 30000, null, "8d117d63-a0d7-4feb-9ef5-3c825669960a");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "f561d3b4-b4ef-4bf8-9329-eb5b0fb77dcf");
                _musicInfo = new RepoItemInfo(this, "Music", ".//select[#'Category']/option[@value='Music']", 30000, null, "ce370699-5570-47a3-9e30-361be8998633");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", 30000, null, "d5ffbd8f-7247-4c82-98a3-251eb7d4dc5f");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "bdbf7342-b34e-4a99-9851-b13aad175f5a");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "f1546ea1-1b74-448e-b587-dd428a297c4b");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "9ea4451a-841b-4b24-b1bb-5fd84dce4b57");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", 30000, null, "6a405196-a67c-45de-8d3e-689f1f192940");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b2ab276e-809d-4d9a-9332-135f838ab46e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b2ab276e-809d-4d9a-9332-135f838ab46e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Fname item.
            /// </summary>
            [RepositoryItem("8d117d63-a0d7-4feb-9ef5-3c825669960a")]
            public virtual Ranorex.InputTag Fname
            {
                get
                {
                    return _fnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Fname item info.
            /// </summary>
            [RepositoryItemInfo("8d117d63-a0d7-4feb-9ef5-3c825669960a")]
            public virtual RepoItemInfo FnameInfo
            {
                get
                {
                    return _fnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("f561d3b4-b4ef-4bf8-9329-eb5b0fb77dcf")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("f561d3b4-b4ef-4bf8-9329-eb5b0fb77dcf")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("ce370699-5570-47a3-9e30-361be8998633")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("ce370699-5570-47a3-9e30-361be8998633")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("d5ffbd8f-7247-4c82-98a3-251eb7d4dc5f")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("d5ffbd8f-7247-4c82-98a3-251eb7d4dc5f")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("bdbf7342-b34e-4a99-9851-b13aad175f5a")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("bdbf7342-b34e-4a99-9851-b13aad175f5a")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("f1546ea1-1b74-448e-b587-dd428a297c4b")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("f1546ea1-1b74-448e-b587-dd428a297c4b")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("9ea4451a-841b-4b24-b1bb-5fd84dce4b57")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("9ea4451a-841b-4b24-b1bb-5fd84dce4b57")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("6a405196-a67c-45de-8d3e-689f1f192940")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("6a405196-a67c-45de-8d3e-689f1f192940")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
